services:
    swiftmailer.transport.eventdispatcher.accord_postmark:
        class: Swift_Events_SimpleEventDispatcher
    
    accord.swift_transport.postmark:
        class: Openbuildings\Postmark\Swift_Transport_PostmarkTransport
        arguments:
            - @swiftmailer.transport.eventdispatcher.accord_postmark
        calls:
            - ['setApi', [@accord.swift_transport.postmark.api]]